"""add genre tags to tracks

Revision ID: f6d9413070ed
Revises: f14b4bf1c5d0
Create Date: 2025-11-26 17:28:19.862688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d9413070ed'
down_revision: Union[str, None] = 'f14b4bf1c5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('genre', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'genre')
    # ### end Alembic commands ###
